spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bionet
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
camel:
  springboot:
    main-run-controller: true